name: Jenkins Job Status Check

on:
  schedule:
    - cron: '*/1 * * * *' # This will check the job status every 1 minutes

jobs:
  check-jenkins-status:
    runs-on: ubuntu-latest
    steps:
      - name: Check Jenkins Job Status
        id: jenkins-status
        run: |
          JOB_NAME="myfirstjob"
          JENKINS_URL="http://45.79.122.237:8080"
          USERNAME="${{ secrets.JENKINS_USER }}"
          TOKEN="${{ secrets.JENKINS_API_TOKEN }}"

          # Get the job status from Jenkins
          STATUS=$(curl -s -u $USERNAME:$TOKEN $JENKINS_URL/job/$JOB_NAME/lastBuild/api/json | jq -r '.result')

          if [ "$STATUS" == "null" ]; then
            echo "Job is running or has never been built."
            STATUS="RUNNING"
          fi

          echo "Job Status: $STATUS"

          # Set the job status as an output
          echo "::set-output name=status::$STATUS"

